source 'https://rubygems.org'

ruby '>= 2.6.10'

gem 'rails', '~> 6.1.7'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.3'

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'ffi', '~> 1.15.5'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
